services:
  readability:
    image: phpdockerio/readability-js-server
    networks:
      - readable
    expose:
      - "3000"
    restart: unless-stopped

  proxy-scanner:
    build:
      context: ./
    develop:
      watch:
        # sync static content
        - path: ./src
          action: sync
          target: /usr/src/app
          ignore:
            - node_modules/

    networks:
      - readable
    depends_on:
      - readability
      - readability-database
      - rss-bridge
    ports:
      - "4912:8080"
    volumes:
      - "./src:/usr/src/app"
    restart: unless-stopped

  readability-database:
    image: mongo
    networks:
      - readable
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - "E:\\NewsDatabase:/data/db"
    ports:
      - 27017:27017
    restart: unless-stopped

  rss-bridge:
    image: rssbridge/rss-bridge:latest
    networks:
      - readable
    volumes:
      - ./rss-bridge/whitelist.txt:/app/whitelist.txt
      - ./rss-bridge/bridges:/app/bridges
    ports:
      - 3939:80
    restart: unless-stopped

  hug:
    build: ./hug/
    command: hug -f hug.py
    networks:
      - readable
    depends_on:
      - readability-database
    ports:
      - 3839:8000
    volumes:
      - ./hug/.:/src
    restart: unless-stopped

  news-scanner:
    build: ./news-scanner/
    container_name: news-scanner
    env_file: ./news-scanner/.env
    networks:
      - readable
    depends_on:
      - readability-database
      - readability
      - rss-bridge
    ports:
      - "4913:8080"
    volumes:
      - "./news-scanner:/app"
      - "./news-scanner/logs:/app/logs"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  readable:
