receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  # Prometheus metrics
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['0.0.0.0:8889']

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

  # Add resource attributes
  resource:
    attributes:
      - key: service.name
        value: news-analysis-system
        action: upsert
      - key: service.version
        value: "1.0.0"
        action: upsert

exporters:
  # Prometheus metrics export
  prometheus:
    endpoint: "0.0.0.0:8889"

  # Debug exporter for testing
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      processors: [batch, resource]
      exporters: [prometheus, debug]

    traces:
      receivers: [otlp]
      processors: [batch, resource]
      exporters: [debug]
